name: Django CI

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/flask.yml'
      - '**.py'
      - 'services/**'
      - 'utilities/**'
      - 'Pipfile'
      - 'Pipfile.lock'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/flask.yml'
      - '**.py'
      - 'services/**'
      - 'utilities/**'
      - 'Pipfile'
      - 'Pipfile.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pipenv'
      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: pipenv install --deploy --dev
      - name: Run Tests
        run: pipenv run python -m unittest
